# Generated by Django 3.2.7 on 2022-08-02 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9A-Z]*$', 'Only uppercase letters and numbers are allowed, no spaces or special characters.')])),
                ('context', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_pattern', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9A-Z]*$', 'Only uppercase letters and numbers are allowed, no spaces or special characters.')])),
                ('active', models.BooleanField(default=True)),
                ('alert_time', models.JSONField()),
                ('precision', models.IntegerField(choices=[(0, 'Equal'), (1, 'Over 80'), (2, 'Over 60')])),
                ('match_by_category', models.BooleanField(default=False)),
                ('any_plate', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
