# Generated by Django 3.2.7 on 2022-08-02 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('alert', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configalert',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camera'),
        ),
        migrations.AddField(
            model_name='configalert',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='core.Category'),
        ),
        migrations.AddField(
            model_name='configalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.entry'),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
