# Generated by Django 3.2.7 on 2021-11-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_entry_category'),
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configalert',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='core.Category'),
        ),
    ]
