# Generated by Django 3.2.7 on 2022-01-23 22:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_category_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alert', '0002_alter_configalert_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9A-Z]*$', 'Only uppercase letters and numbers are allowed, no spaces or special characters.')])),
                ('context', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera')),
                ('related_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.entry')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
