# Generated by Django 3.2.7 on 2021-10-05 23:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9A-Z\\s-]*$', 'Only uppercase letters, numbers and spaces allowed')]),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9A-Z\\s-]*$', 'Only uppercase letters, numbers and spaces allowed')])),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9A-Z\\s-]*$', 'Only uppercase letters, numbers and spaces allowed')])),
                ('linked_email_account', models.EmailField(max_length=254)),
                ('agent_address', django_google_maps.fields.AddressField(max_length=200)),
                ('agent_geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100)),
                ('config_added_info', models.JSONField(blank=True, null=True)),
                ('config_ui', models.JSONField(blank=True, null=True)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.domain')),
            ],
        ),
    ]
