# Generated by Django 3.2.7 on 2021-10-06 00:20

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211005_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent_address',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='agent_geolocation',
        ),
        migrations.AddField(
            model_name='agent',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
    ]
