# Generated by Django 3.2.7 on 2021-10-17 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211010_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='key_file_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[\\w\\-. ]+$', 'Invalid file name')]),
        ),
        migrations.AddField(
            model_name='agent',
            name='ssh_reverse_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.domain'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agent'),
        ),
    ]
