# Generated by Django 3.2.7 on 2021-10-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211017_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='domain',
        ),
    ]
