# Generated by Django 3.2.7 on 2021-10-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='ssh_reverse_url',
        ),
        migrations.AddField(
            model_name='agent',
            name='ssh_reverse_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='ssh_reverse_port',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
