# Generated by Django 3.2.7 on 2021-10-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_local_link_camera_local_link1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='local_link1',
            new_name='local_link',
        ),
    ]
