# Generated by Django 3.2.7 on 2021-11-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_entry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='best_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
