# Generated by Django 3.2.7 on 2021-11-17 20:58

import core.custom
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_entry_best_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addedinfo',
            options={'verbose_name_plural': 'added info'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name_plural': 'meta data'},
        ),
        migrations.AlterField(
            model_name='metadata',
            name='meta_data',
            field=models.JSONField(validators=[core.custom.JSONSchemaValidator(limit_value={'type': 'object'})]),
        ),
    ]
