# Generated by Django 3.2.7 on 2021-11-30 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_category_unique_name_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agent'),
        ),
    ]
